config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :books, only: [:index, :show, :edit, :update, :create, :destroy]
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top,:about]
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = @book.user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def new
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else 
      @books = Book.all
      @user = User.find(current_user.id)
      puts @book.errors.full_messages
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    unless @user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    puts @book.errors.full_messages
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      puts @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "削除が完了しました。"
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <div class="form-group"> <label for="inputName">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputName", class: "form-control" %></div>

  <div class="form-group"> <label for="inputBody">Opinion</label>
  <%= f.text_field :body, class: "form-control" %></div>
  <div class="form-group"><%= f.submit "Update Book", class: "btn btn-success" %></div>
<% end %>

<%= link_to 'Show', book_path(@book) %> |
<%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render'users/user',user: current_user, book: @book %>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr><th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th></tr>
  </thead>
  <tbody>
<% @books.each do |book| %>
    <tr><td><%= link_to user_path(book.user) do %><%= image_tag book.user.get_profile_image %><% end %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render'users/user',user: @user, book: @book %>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<%= render'users/user',user: @user, book: @book_new %>
<div class="col-md-8 offset-md-1">
  <h1>Book detail</h1>
  <table class="table table-hover table-inverse">
    <thead>
    </thead>
    <tbody>
      <tr><td><%= image_tag @user.get_profile_image %>
      <br>
      <%= link_to @book.user.name, user_path(@book.user) %>
      </td>
<td><%= link_to @book.title, book_path(@book.id) %></td>
<td><%= @book.body %></td>

<% if @book.user == current_user %>
    <td><%= link_to 'Edit', edit_book_path(@book), class:"btn btn-success" %></td>
    <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に削除しますか？'}, class:"btn btn-danger" %></td>
  <% end %>

</tr>
    </tbody>
  </table>
      </div>
    </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
<h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
  </div>
  <div class="row">
    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/982479bf78.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <!--#%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>-->
  <body>

  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in?%>
          <li>
            <%= link_to user_path(current_user.id), class:"nav-link text-light" do %><i class="fa-solid fa-home"></i>Home<% end %>
          </li>
          <li>
            <%= link_to users_path, class:"nav-link text-light" do %><i class="fa-solid fa-users"></i>Users<% end %>
          </li>
          <li>
            <%= link_to books_path, class:"nav-link text-light" do %><i class="fa-solid fa-book-open"></i>Books<% end %>
            </li>
          <li>
            <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %><i class="fa-solid fa-sign-out-alt"></i>Log out<% end %></li>
          <% else %>
          <li>
            <%= link_to root_path, class:"nav-link text-light" do %><i class="fa-solid fa-home"></i>Home<% end %>
          </li>
          <li>
            <%= link_to home_about_path, class:"nav-link text-light" do %><i class="fa-solid fa-link"></i>About<% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %><i class="fa-solid fa-user-plus"></i>Sign up<% end %>
            </li>
          <li>
            <%= link_to user_session_path, class: "nav-link text-light" do %><i class="fa-solid fa-right-to-bracket"></i>Log in<% end %>
          <%end%>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <main>
      <%= flash[:notice] %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<div class="col-md-3">
<h1>Users info</h1>

<div>
  <%= image_tag user.get_profile_image %>
  <table class="table">
  <tbody>
    <tr></tr>
    <tr><th>name</th>
  <th><%= user.name %></th></tr>
  <tr><th>introduction</th>
  <th><%= user.introduction %></th></tr></tbody></table>
  <p><%= link_to edit_user_path(user.id) ,class:"btn btn-outline-secondary btn-block" do %><i class="fa-solid fa-user-gear"></i><% end %></p></div>


<h1>New book</h1>

<%= form_with model: book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Opinion</p>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class:"btn btn-success" %>
  
<% end %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
  <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    <% end %>
<%= form_with model: @user do |f| %>
 <div class="form-group"> <label for="inputName">Name</label>
  <%= f.text_field :name, class: "form-control"  %></div>


  <div class="form-group"><label for="inputImage">Image</label>
  <%= f.file_field :profile_image,accept: "image/*", class: "form-control-file" %></div>


  <div class="form-group"><label for="inputBody">Introduction</label>
  <%= f.text_area :introduction, class: "form-control"%></div>

  <div class="form-group"><%= f.submit 'Update User', class: "btn btn-secondary" %></div>

<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'user',user: @user, book: @book %>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
</thead>
<% @users.each do |user| %>
<tbody>
  <td><%= image_tag user.get_profile_image %></td>
  <td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>

<% end %>
</tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'user',user: @user, book: @book %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<% @books.each do |book| %>
<tbody>
  <tr>
    <td>
  <p>
    <%= link_to user_path(book.user_id) do %>
    <%= image_tag book.user.get_profile_image %>
    <% end %>
  </p>
  </td>

  <td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>

<% end %>
  </tr>
</tbody>
</table>
    </div>
  </div>
</div>